version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: wpmodbauto    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abvn1234
      MONGO_INITDB_DATABASE: mongodb
    ports:
      - "27018:27017"
    networks:
      - wqnetwork

  jupyter:
    image: mindartedu/mindart_jpnb:latest
    container_name: wpjpauto
    ports:
      - "8887:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: abvn1234
    networks:
      - wqnetwork
      
  python:
    image: ghcr.io/mindartedu/wqpyauto:latest
    #image: wqpyauto:latest
    container_name: wqpyauto_tr
    networks:
      - wqnetwork
networks:
  wqnetwork:
    driver: bridge
